### ISSUE TITLE
Remove shrinkwrap from conda-forge - migrating to bioconda

### ISSUE THREAD

**Issue by matuskosut** [conda-forge/shrinkwrap-feedstock#1]
Bioconda recipe: https://github.com/bioconda/bioconda-recipes/pull/25032

It turns out shrinkwrap fits more into bioconda (genomics). Need to link up the dependency on htslib at bioconda too. 

It was created just 2 days ago, don't expect issues that wouldn;t be solved with pointing the source of package to bioconda.

**Comment by matuskosut** [comment]
Sorry for the hassle, @ocefpaf could you maybe help out with this one?

**Comment by ocefpaf** [comment]
conda-forge is "generic" and this is a good fit here too. I do not that bioconda folks have a policy on what they want on conda-forge and what they want on bioconda but I don't really know that policy. I'll defer it to @mbargull to comment on this one.

**Comment by mbargull** [comment]
Looking at the description of https://github.com/jonathonl/shrinkwrap, to me it looks to be more of a general-purpose software and as such is a good fit to remain on conda-forge.
(Do feel free to re-open this issue or ask additional questions if anything is unclear!)
